/* eslint-disable */
// @ts-nocheck
// Auto-generated from _tokens.scss - DO NOT EDIT
export const Tokens = {
  borderRadiusCircle: '500px',
  borderRadiusXs: '2px',
  borderRadiusS: '4px',
  borderRadiusM: '8px',
  borderRadiusL: '12px',
  colorBackground: '#fff',
  colorBackgroundActive: '#21225f',
  colorBackgroundSecondary: '#f8f9fc',
  colorElevationSurface: '#fff',
  colorBorder: '#b2b2e4',
  colorBorderSecondary: '#e2e4f0',
  colorBorderActive: '#fff',
  colorIconSubtle: '#6d6e9c',
  colorSecondary500: '#2d2e83',
  colorText: '#21225f',
  colorTextActive: '#f8f9fc',
  colorTextSubtle: '#6d6e9c',
  colorTextError: '#a00',
  containerMaxWidth: '835px',
  containerPadding: '24px',
  size1Px: '1px',
  size2Px: '2px',
  size4Px: '4px',
  size8Px: '8px',
  size12Px: '12px',
  size16Px: '16px',
  size20Px: '20px',
  size24Px: '24px',
  size32Px: '32px',
  size36Px: '36px',
  size48Px: '48px',
  size64Px: '64px',
  spacing1Px: '1px',
  spacing2Px: '2px',
  spacing4Px: '4px',
  spacing8Px: '8px',
  spacing12Px: '12px',
  spacing16Px: '16px',
  spacing20Px: '20px',
  spacing24Px: '24px',
  spacing32Px: '32px',
  spacing36Px: '36px',
  spacing48Px: '48px',
  spacing64Px: '64px',
  fontFamilyNormal:
    "'Inter',\r\n  -apple-system,\r\n  blinkmacsystemfont,\r\n  'Segoe UI',\r\n  sans-serif",
  fontFamilyMonospace: "'Monaco', 'Courier New', monospace",
  fontSizeS: '12px',
  fontSizeM: '14px',
  fontSizeL: '16px',
  fontSizeXl: '18px',
  fontSizeXxl: '20px',
  fontWeightLight: '300',
  fontWeightRegular: '400',
  fontWeightMedium: '500',
  fontWeightSemibold: '600',
  fontWeightBold: '700',
  lineHeightM: '20px',
} as const;

export type TokenKey = keyof typeof Tokens;
